/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostPathRouteImport } from './routes/$postPath'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminThemeRouteImport } from './routes/admin/theme'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCallbackRouteImport } from './routes/admin/callback'
import { Route as AdminPostsPostIdRouteImport } from './routes/admin/posts.$postId'

const PostPathRoute = PostPathRouteImport.update({
  id: '/$postPath',
  path: '/$postPath',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/admin/theme',
  path: '/admin/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCallbackRoute = AdminCallbackRouteImport.update({
  id: '/admin/callback',
  path: '/admin/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsPostIdRoute = AdminPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AdminPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$postPath': typeof PostPathRoute
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin': typeof AdminIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$postPath': typeof PostPathRoute
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin': typeof AdminIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$postPath': typeof PostPathRoute
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$postPath'
    | '/admin/callback'
    | '/admin/login'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin'
    | '/admin/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$postPath'
    | '/admin/callback'
    | '/admin/login'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin'
    | '/admin/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/$postPath'
    | '/admin/callback'
    | '/admin/login'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin/'
    | '/admin/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostPathRoute: typeof PostPathRoute
  AdminCallbackRoute: typeof AdminCallbackRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$postPath': {
      id: '/$postPath'
      path: '/$postPath'
      fullPath: '/$postPath'
      preLoaderRoute: typeof PostPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/admin/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/callback': {
      id: '/admin/callback'
      path: '/admin/callback'
      fullPath: '/admin/callback'
      preLoaderRoute: typeof AdminCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$postId': {
      id: '/admin/posts/$postId'
      path: '/$postId'
      fullPath: '/admin/posts/$postId'
      preLoaderRoute: typeof AdminPostsPostIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
  }
}

interface AdminPostsRouteChildren {
  AdminPostsPostIdRoute: typeof AdminPostsPostIdRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsPostIdRoute: AdminPostsPostIdRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostPathRoute: PostPathRoute,
  AdminCallbackRoute: AdminCallbackRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
